# Generated by Django 5.2.7 on 2025-10-10 02:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefone')),
                ('company', models.CharField(blank=True, max_length=120, verbose_name='Empresa')),
                ('status', models.CharField(choices=[('NEW', 'Novo'), ('QLF', 'Qualidade'), ('WON', 'Ganho'), ('LST', 'Perdido'), ('CLD', 'Frio')], default='NEW', max_length=3)),
                ('source', models.CharField(choices=[('WEB', 'Website'), ('ADS', 'Anúncio'), ('REF', 'Indicação'), ('EVT', 'Evento'), ('OTH', 'Outro')], default='OTH', max_length=3)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor estimado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='leads.tag')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('email', ''), _negated=True), fields=('email', 'company'), name='unique_lead_email_per_company')],
            },
        ),
    ]
