# Generated by Django 5.2.7 on 2025-10-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_rename_update_at_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='lead',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
